const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirt for men',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 10,
      description: 'High quality shirt for men',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 250,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 18,
      description: 'High quality pant for men',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 200,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 10,
      description: 'High quality pant for men',
    },
  ],
};

export default data;
